
environment: dev
applicationName: shephard-core

# Database settings.
database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: shepherd
  # the password
  password: shepherd
  # the JDBC URL
  url: jdbc:mysql://shepherd.cpdwhawnvczl.us-east-1.rds.amazonaws.com:3306/shepherd_master

  initialSize: 1

server:
  rootPath: /shephard-core
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: INFO
    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: INFO

# Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/shephard-core-application-%d{yyyy-MM-dd}.log.gz
# Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/shephard-core-application-%d{yyyy-MM-dd}-%i.log.gz
# Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/shephard-core-application-%i.log.gz

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/shephard-core-application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

datasource :
  prefix: mongodb
  user: ashutosh
  password: xyz
  clusters:
    - shepherd-cluster0-shard-00-00-lovgv.mongodb.net:27017
    - shepherd-cluster0-shard-00-01-lovgv.mongodb.net:27017
    - shepherd-cluster0-shard-00-02-lovgv.mongodb.net:27017
  path: /test
  params: ssl=true&replicaSet=Shepherd-Cluster0-shard-0&authSource=admin&retryWrites=true
  db_name: shepherd
  collection_name: execution_details